### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by murraycadzow** [theboocock/studyGroup#53]
Hi everyone,

we are migrating to http://otagostudygroup.github.io/studyGroup/ as the new site please update your bookmarks

You will also have to 'watch' the new repo at https://github.com/otagostudygroup/studyGroup
to stay current with what is happening

Murray

**Comment by johnfrombluff** [comment]
Thanks.  But the link where it says:

"Head over to GitHub and watch our repository, like this:" is broken.

**Comment by murraycadzow** [comment]
fixed on  https://github.com/otagostudygroup/studyGroup
